/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UeberMichRouteImport } from './routes/ueber-mich'
import { Route as PreiseRouteImport } from './routes/preise'
import { Route as LeistungenRouteImport } from './routes/leistungen'
import { Route as LeistungenKiAutomatisierungRouteImport } from './routes/leistungen.ki-automatisierung'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'

const UeberMichRoute = UeberMichRouteImport.update({
  id: '/ueber-mich',
  path: '/ueber-mich',
  getParentRoute: () => rootRouteImport,
} as any)
const PreiseRoute = PreiseRouteImport.update({
  id: '/preise',
  path: '/preise',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenRoute = LeistungenRouteImport.update({
  id: '/leistungen',
  path: '/leistungen',
  getParentRoute: () => rootRouteImport,
} as any)

const LeistungenKiAutomatisierungRoute = LeistungenKiAutomatisierungRouteImport.update({
  id: '/leistungen/ki-automatisierung',
  path: '/leistungen/ki-automatisierung',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRoute
  '/leistungen/ki-automatisierung': typeof LeistungenKiAutomatisierungRoute
  '/preise': typeof PreiseRoute
  '/ueber-mich': typeof UeberMichRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRoute
  '/leistungen/ki-automatisierung': typeof LeistungenKiAutomatisierungRoute
  '/preise': typeof PreiseRoute
  '/ueber-mich': typeof UeberMichRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRoute
  '/leistungen/ki-automatisierung': typeof LeistungenKiAutomatisierungRoute
  '/preise': typeof PreiseRoute
  '/ueber-mich': typeof UeberMichRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/impressum'
    | '/kontakt'
    | '/leistungen'
    | '/leistungen/ki-automatisierung'
    | '/preise'
    | '/ueber-mich'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/impressum'
    | '/kontakt'
    | '/leistungen'
    | '/leistungen/ki-automatisierung'
    | '/preise'
    | '/ueber-mich'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/impressum'
    | '/kontakt'
    | '/leistungen'
    | '/leistungen/ki-automatisierung'
    | '/preise'
    | '/ueber-mich'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  ImpressumRoute: typeof ImpressumRoute
  KontaktRoute: typeof KontaktRoute
  LeistungenRoute: typeof LeistungenRoute
  LeistungenKiAutomatisierungRoute: typeof LeistungenKiAutomatisierungRoute
  PreiseRoute: typeof PreiseRoute
  UeberMichRoute: typeof UeberMichRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ueber-mich': {
      id: '/ueber-mich'
      path: '/ueber-mich'
      fullPath: '/ueber-mich'
      preLoaderRoute: typeof UeberMichRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preise': {
      id: '/preise'
      path: '/preise'
      fullPath: '/preise'
      preLoaderRoute: typeof PreiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen': {
      id: '/leistungen'
      path: '/leistungen'
      fullPath: '/leistungen'
      preLoaderRoute: typeof LeistungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/ki-automatisierung': {
      id: '/leistungen/ki-automatisierung'
      path: '/leistungen/ki-automatisierung'
      fullPath: '/leistungen/ki-automatisierung'
      preLoaderRoute: typeof LeistungenKiAutomatisierungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  ImpressumRoute: ImpressumRoute,
  KontaktRoute: KontaktRoute,
  LeistungenRoute: LeistungenRoute,
  LeistungenKiAutomatisierungRoute: LeistungenKiAutomatisierungRoute,
  PreiseRoute: PreiseRoute,
  UeberMichRoute: UeberMichRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
